
name: Publish Artifacts
on:
  release:
    types: [published, created]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup nix-shell
      uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Run tests
      uses: ZenithalHourlyRate/nix-shell-action@v4
      with:
        file: shell.nix
        script: |
          make nix-test

    - name: Build artifacts
      uses: ZenithalHourlyRate/nix-shell-action@v4
      with:
        file: shell.nix
        script: |
          make nix-build

    - name: Upload artifacts
      uses: skx/github-action-publish-binaries@release-1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        releaseId: ${{ needs.create_release.outputs.id }}
        args: 'sctk'
